name: Build and upload pdf
on:
  push:
    paths:
      - thesis/**
    # branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: thesis/
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: thesis/main.pdf
