name: Build and release PDF
on:
  push:
    paths:
      - 'thesis/**'
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to make releases
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Remove old releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: thesis/

      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: PDF
          body: The latest PDF
          files: thesis/main.pdf
